### ISSUE TITLE
Base env

### ISSUE THREAD

**Issue by jeremyforest** [neurogym/neurogym#10]
Base environment should contain all the variables to run an environment without any trials. I can work on getting the required variables in the BaseEnv Class. I don't think it would break any other env as TrialEnv inherit from BaseEnv but what do you think ? 

As an example: self.t, self.tmax, the env variables (ob and act dicts), self.rewards ... all should go in BaseEnv and then TrialEnv inherit them from there. Sounds ok ?
Also true for render, step, _step functions.

**Comment by gyyang** [comment]
Thanks! I would some of these attributes to BaseEnv in b79b4ceac693218348f398b6ec4b5b4b122e8468
