### ISSUE TITLE
Neurogym installation/version issues

### ISSUE THREAD

**Issue by mikailkhona** [neurogym/neurogym#34]
Hi,
I have neurogym version '0.0.1'.
I suspect I've made some mistake while installing the package.
Just importing the package gives me the following error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-e2ab0f5eb152> in <module>
     10 import torch.nn as nn
     11 import gym
---> 12 import neurogym as ngym
     13 from neurogym.wrappers import ScheduleEnvs
     14 from neurogym.utils.scheduler import RandomSchedule

~/neurogym/neurogym/__init__.py in <module>
      4 from neurogym.core import TrialEnv
      5 from neurogym.core import TrialWrapper
----> 6 import neurogym.utils.spaces as spaces
      7 from neurogym.envs.registration import make
      8 from neurogym.envs.registration import register

~/neurogym/neurogym/utils/spaces.py in <module>
----> 1 from gym.spaces.space import Space
      2 from gym.spaces.box import Box as GymBox
      3 from gym.spaces.discrete import Discrete as GymDiscrete
      4 from gym.spaces.multi_discrete import MultiDiscrete
      5 from gym.spaces.multi_binary import MultiBinary

ModuleNotFoundError: No module named 'gym.spaces.space'

**Comment by gyyang** [comment]
I'm sorry about the issue you're having. I have updated the main branch with some bug fix. Can you try to reinstall it?
```
git clone https://github.com/neurogym/neurogym.git
cd neurogym
pip install -e .
```

If this doesn't work, can you report the gym version by typing in command line:
`python -c 'import gym; print(gym.__version__)'`

Thanks!

**Comment by mikailkhona** [comment]
Thanks for the help,
I reinstalled neurogym and the version is now '0.10.9' - 

python -c 'import gym; print(gym.__version__)'
0.10.9

However, now when import, I see this error:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-14-a3c412ddddf1> in <module>
      7 import gym
      8 import neurogym as ngym
----> 9 from neurogym.wrappers.block import MultiEnvs
     10 from models import RNNNet, get_performance
ModuleNotFoundError: No module named 'neurogym.wrappers'

So sorry for all the trouble, 
Mikail

**Comment by gyyang** [comment]
Can you try updating gym by running in command line `pip install -U gym`? Can you also share your Python version? Thanks.

**Comment by mikailkhona** [comment]
Thanks for all the help! It's now 0.18.3 and everything is working fine now!
Have a good night and weekend,
Mikail
