### ISSUE TITLE
action_space no more initialized to None in base Env for the latest versions of gym

### ISSUE THREAD

**Issue by nacloos** [neurogym/neurogym#36]
This caused the following error when running test_envs.py with gym 0.23.1

AttributeError: 'AntiReach' object has no attribute 'action_space'

which is raised when calling seed() in the constructor of TrialEnv.

I commented this call to seed in commit 856957985badc56d3a6e2e286a31e00982931cd7. Now all the tests in test_envs.py pass for all environments in the main branch (the CueSetGo env in the dev branch is raising another error).

There might be other modifications to do in the code due to this change with observation_space and action_space in the latest versions of gym.

**Comment by manuelmolano** [comment]
Doesn't this affect the generation of random numbers? Shouldn't we call seed at some point?

**Comment by gcroci2** [comment]
Is this still relevant? Otherwise, we can close it @nacloos @manuelmolano

**Comment by gcroci2** [comment]
I think this is not relevant anymore since we are migrating to gymnasium (already on `dev` branch).
