### ISSUE TITLE
neurogym.TrialEnv not found

### ISSUE THREAD

**Issue by Ctrl408** [neurogym/neurogym#43]
Traceback:
`   ImportError                
Traceback (most recent call last)
[<ipython-input-8-e6a9ab4ca9e3>](https://localhost:8080/#) in <module>
      1 import neurogym as ngym
----> 2 from neurogym import TrialEnv
      3 
      4 class MyTrialEnv(TrialEnv):
      5     def __init__(self):

ImportError: cannot import name 'TrialEnv' from 'neurogym' (unknown location)   `

 couldn't find any files or functions titled with the name

**Comment by fengxunling** [comment]
I have the same problem as you.

**Comment by Ctrl408** [comment]
After some long search, found the base class at core.py
Probably you're from https://colab.research.google.com/drive/1UL8DkhThsepHxPTVIPg8DpzVgCge6_7q

Change the import from 'import nerogym.TrialEnv' to  'from neurogym.core import TrialEnv'
