### ISSUE TITLE
installations fails 

### ISSUE THREAD

**Issue by jmourabarbosa** [neurogym/neurogym#44]
I can't install neurogym using: 

pip install gym  
git clone https://github.com/gyyang/neurogym.git 
cd neurogym/
pip install -e .

I get: 

>>> import neurogym 
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/Users/jbarbosa/neurogym/neurogym/__init__.py", line 7, in <module>
  from neurogym.envs.registration import make
 File "/Users/jbarbosa/neurogym/neurogym/envs/registration.py", line 235, in <module>
  _all_gym_envs = [env.id for env in gym.envs.registry.all()]
AttributeError: 'dict' object has no attribute 'all'

Within a just created conda environment with python 3.8

**Comment by nacloos** [comment]
registry.all is deprecated in the latest versions of gym
I just made a pull request to fix that

**Comment by jmourabarbosa** [comment]
Thanks! Oddly, it works in colabs but not locally.
