### ISSUE TITLE
Using Neurogym with stable-baselines3

### ISSUE THREAD

**Issue by fspinar** [neurogym/neurogym#49]
Hi all, 

I have been trying to use Neurogym with stable-baselines3. However I am getting issues mostly due to the way that Neurogym calls stable-baselines. Has anyone tried using stable-baselines3 ? I am wondering if I should downgrade or should try to solve the issues I am getting. 

Thanks,
Fatih.

**Comment by nacloos** [comment]
Hi Fatih, can you share which specific issues you are getting?

**Comment by nacloos** [comment]
It's probably an issue with the breaking changes in the different versions of gym.
I was able to run your code with these versions:
gym                 0.21.0
neurogym            0.0.2
numpy               1.19.5
pandas              1.4.4
stable-baselines3   1.6.0
torch               2.2.0

**Comment by nacloos** [comment]
I also don't think stable-baselines3 natively supports recurrent policies but you can have a look here: https://sb3-contrib.readthedocs.io/en/master/modules/ppo_recurrent.html

**Comment by fspinar** [comment]
Thanks a lot @nacloos ! It worked when I used gym and stable-baselines3 versions that you mentioned above. 
However, when I tried the last part of the tutorial, the Visualize Results title, I am getting a new error:

Here is the code in the tutorial:
https://neurogym.github.io/example_neurogym_rl.htm

env = gym.make(name, **kwargs)
# print task properties
print(env)
# wrapp task with pass-reward wrapper
env = pass_reward.PassReward(env)
env = DummyVecEnv([lambda: env])
# plot example trials with random agent
data = ngym.utils.plot_env(env, fig_kwargs={'figsize': (12, 12)}, num_steps=100, ob_traces=['Fixation cue', 'Stim 1','Stim 2',  'Previous reward'], model=model)
plt.savefig('figure2.png')  # Saves the figure to a file

Here is my code:

import gym
import neurogym as ngym
from neurogym.wrappers import pass_reward
import warnings
import matplotlib.pyplot as plt  # Add this line to import matplotlib.pyplot
from stable_baselines3 import A2C
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import DummyVecEnv
warnings.filterwarnings('ignore')
from gym import Wrapper


# Task name
name = 'PerceptualDecisionMaking-v0'
# task specification (here we only specify the duration of the different trial periods)
timing = {'fixation': ('constant', 300),
          'stimulus': ('constant', 500),
          'decision': ('constant', 300)}
kwargs = {'dt': 100, 'timing': timing}
# build task
env = gym.make(name, **kwargs)
# print task properties
print(env)
# wrapp task with pass-reward wrapper
env = pass_reward.PassReward(env)
# plot example trials with random agent
data = ngym.utils.plot_env(env, fig_kwargs={'figsize': (12, 12)}, num_steps=100, ob_traces=['Fixation cue', 'Stim 1', 'Stim 2', 'Previous reward'])
plt.savefig('figure.png')  # Saves the figure to a file

# Assuming 'env' is already created as in your previous messages
# For this example, let's just create a placeholder for 'env'
env_id = 'PerceptualDecisionMaking-v0'
env = DummyVecEnv([lambda: env])  # Note: env is directly passed here

# When using LSTM, you should inform SB3 that you are using a recurrent policy
# Note: 'policy_kwargs' is used to specify the LSTM layers within the policy
policy_kwargs = dict(
    net_arch=[{"pi": [64, 64, 'lstm'], "vf": [64, 64, 'lstm']}],
)

model = A2C('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=10000, log_interval=1000)
env.close()
env = gym.make(name, **kwargs)
# print task properties
print(env)
# wrapp task with pass-reward wrapper
env = pass_reward.PassReward(env)
env = DummyVecEnv([lambda: env])
# plot example trials with random agent
data = ngym.utils.plot_env(env, fig_kwargs={'figsize': (12, 12)}, num_steps=100, ob_traces=['Fixation cue', 'Stim 1','Stim 2',  'Previous reward'], model=model)
plt.savefig('figure2.png')  # Saves the figure to a file


Here is the error:


C:\ProgramData\anaconda3\python.exe D:\IRNN\trial1.py 
<OrderEnforcing<PerceptualDecisionMaking>>
Using cpu device
------------------------------------
| time/                 |          |
|    fps                | 974      |
|    iterations         | 1000     |
|    time_elapsed       | 5        |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -0.00856 |
|    explained_variance | 0.0136   |
|    learning_rate      | 0.0007   |
|    n_updates          | 999      |
|    policy_loss        | 0.000193 |
|    value_loss         | 0.0388   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 969      |
|    iterations         | 2000     |
|    time_elapsed       | 10       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -0.079   |
|    explained_variance | 0.454    |
|    learning_rate      | 0.0007   |
|    n_updates          | 1999     |
|    policy_loss        | 0.0155   |
|    value_loss         | 0.199    |
------------------------------------
<OrderEnforcing<PerceptualDecisionMaking>>
Traceback (most recent call last):
  File "D:\IRNN\trial1.py", line 62, in <module>
    data = ngym.utils.plot_env(env, fig_kwargs={'figsize': (12, 12)}, num_steps=100, ob_traces=['Fixation cue', 'Stim 1','Stim 2',  'Previous reward'], model=model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\fatih\neurogym\neurogym\utils\plotting.py", line 48, in plot_env
    data = run_env(env=env, num_steps=num_steps, num_trials=num_trials,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\fatih\neurogym\neurogym\utils\plotting.py", line 83, in run_env
    if len(_states) > 0:
       ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

Process finished with exit code 1

Do you have any suggestions about this part? Or could you try if you can run this ?

Thanks a lot again, it is really helpful.

Fatih

**Comment by fspinar** [comment]
I think I got it working by adding some wrapper functions to make sure compatibility... Thanks a lot for helping!!!

Fatih.
