### ISSUE TITLE
Using gymnasium instead of gym 

### ISSUE THREAD

**Issue by fspinar** [neurogym/neurogym#51]
Hi all, 

If my understanding is right, Open AI gym is basically carried to gymnasium, and gym is no longer maintained. 
However, Neurogym is built on gym, not gymnasium, right?

If my understanding is correct, is this something that we should consider while setting up Neurogym? 
For instance, is it possible to install or wrap it such that it is compatible with Gymnasium? 

I am new to all of these, so please let me know if my understanding is not right; or; if this compatibility issue is not a serious concern.

Thanks!
Fatih.

**Comment by nacloos** [comment]
Hi Fatih,

You are right. Neurogym is built with gym but it is possible to wrap it to be compatible with Gymnasium.
See: https://gymnasium.farama.org/content/gym_compatibility/
