### ISSUE TITLE
Add `cffconvert.yml` and `CITATION.cff` files

### ISSUE THREAD

**Issue by gcroci2** [neurogym/neurogym#73]
**[<img src="https://avatars.githubusercontent.com/u/55382553?s=17&v=4" width="17" height="17"> @gcroci2](https://github.com/gcroci2)** cloned issue [ANNUBS/neurogym#43](https://github.com/ANNUBS/neurogym/issues/43) on 2024-09-13: 

> See [the old annubes repository](https://github.com/ANNUBS/annubes/blob/main/.github/workflows/cffconvert.yml) as an example.

**Comment by DaniBodor** [comment]
@gcroci2 , this and #72 did not automatically close when the PR got merged. I remember you fixed a similar issue for another project once, but I don't remember what the problem was. Do you know whether it could be the same here?

**Comment by gcroci2** [comment]
I went through the project settings, and they are correct (automation should be in place), so I'm not sure why they're not automatically closing. It's happening to me as well within this project.
